### ISSUE TITLE
Current Cabal config doesn't like the latest hspec.

### ISSUE THREAD

**Issue by madscientist42** [adamwalker/clash-riscv#1]
Latest pulled from this repository with hspec pulled in with Cabal.  This is the choke on build:

rejecting: hspec-2.4.2/installed-JOW... (conflict: clash-riscv => hspec>=2.3
&& <2.4)

I'd think you'd need to try to keep it current with what's obtainable...

**Comment by adamwalker** [comment]
Bumped hspec dep upper bound

**Comment by madscientist42** [comment]
Many thanks!  Looking forward to trying the code out.
